import React from 'react';
import {Linking, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {Icon} from '../icons/Icon';
import {colors} from '../theme';

export function AboutScreen() {
  return <ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><View style={styles.logo}><Icon name="logo" size={46} color={colors.violetSoft}/></View><Text style={styles.name}>OpenFlux</Text><Text style={styles.version}>ANDROID CLIENT · 1.0.0</Text></View><View style={styles.card}><Icon name="shield" size={22} color={colors.green}/><Text style={styles.cardTitle}>Core + Android VPN</Text><Text style={styles.copy}>This client connects Android's system VpnService TUN directly to the existing OpenFlux transport pipeline. It does not run a local SOCKS proxy.</Text></View><View style={styles.card}><Icon name="server" size={22} color={colors.cyan}/><Text style={styles.cardTitle}>Exit node required</Text><Text style={styles.copy}>Configure the same Yandex document URL or MAX credentials on this device and on the Linux exit node. A public VPS IP is sufficient; a domain is optional.</Text></View><View style={styles.card}><Icon name="warning" size={22} color={colors.amber}/><Text style={styles.cardTitle}>Educational and authorised use</Text><Text style={styles.copy}>OpenFlux is open-source network-stack research software. Use it only on systems, accounts and networks you own or are explicitly authorised to test.</Text></View><Pressable onPress={() => void Linking.openURL('https://github.com/p1neappleXpress/OpenFlux')} style={styles.link}><Text style={styles.linkText}>VIEW OPEN-SOURCE PROJECT</Text><Icon name="connection" size={18} color={colors.violetSoft}/></Pressable><Text style={styles.footer}>GPL-3.0-or-later · No traffic payloads or credentials are shown in the app logs.</Text></ScrollView>;
}
const styles = StyleSheet.create({scroll: {padding: 22, paddingBottom: 30}, hero: {alignItems: 'center', paddingTop: 20, paddingBottom: 30}, logo: {width: 88, height: 88, backgroundColor: '#19152A', borderRadius: 28, alignItems: 'center', justifyContent: 'center', borderColor: '#3D2D74', borderWidth: 1}, name: {fontSize: 30, color: colors.text, fontWeight: '800', marginTop: 15, letterSpacing: -.8}, version: {color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginTop: 7}, card: {backgroundColor: colors.surface, borderRadius: 20, borderColor: colors.border, borderWidth: 1, padding: 17, marginBottom: 12}, cardTitle: {color: colors.text, fontSize: 15, fontWeight: '800', marginTop: 12}, copy: {color: colors.muted, lineHeight: 19, fontSize: 13, marginTop: 6}, link: {height: 54, paddingHorizontal: 18, backgroundColor: '#18152A', borderColor: '#45317E', borderWidth: 1, borderRadius: 17, alignItems: 'center', justifyContent: 'space-between', flexDirection: 'row', marginTop: 12}, linkText: {color: colors.violetSoft, fontWeight: '900', fontSize: 11, letterSpacing: 1}, footer: {color: colors.muted, textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 23}});
