import React from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {ConnectionOrb} from '../components/ConnectionOrb';
import {Stat} from '../components/Stat';
import {Icon} from '../icons/Icon';
import {colors} from '../theme';
import {VpnState} from '../types';

const bytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`;
const duration = (seconds: number) => `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds / 60) % 60).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
export function HomeScreen({state, onConnect, onDisconnect, onSettings}: {state: VpnState; onConnect: () => void; onDisconnect: () => void; onSettings: () => void}) {
  const {config, status} = state;
  const active = ['STARTING', 'CONNECTING', 'CONNECTED', 'DISCONNECTING'].includes(status.state);
  const connected = status.state === 'CONNECTED';
  const configured = config.transport === 'max' ? Boolean(config.maxToken && config.maxUid) : Boolean(config.yandexUrl);
  const transportLabel = config.transport === 'max' ? 'MAX Messenger' : config.transport === 'vyandex' ? 'Yandex Docs (VOLGA)' : 'Yandex Docs (legacy)';
  return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.brand}><Icon name="logo" size={29} color={colors.violetSoft}/><Text style={styles.wordmark}>OpenFlux</Text></View><Pressable onPress={onSettings} style={styles.settings}><Icon name="settings" size={21} color={colors.muted}/></Pressable></View>
    <ConnectionOrb state={status.state}/>
    <Text style={styles.title}>{connected ? 'Protected by OpenFlux' : 'Your private route, ready'}</Text>
    <Text style={styles.subtitle}>{status.message || 'Configure a transport, then connect.'}</Text>
    {status.state === 'ERROR' && <View style={styles.error}><Icon name="warning" size={17} color={colors.red}/><Text style={styles.errorText}>{status.message}</Text></View>}
    <Pressable disabled={status.state === 'DISCONNECTING'} onPress={active ? onDisconnect : onConnect} style={[styles.power, connected && styles.powerOn, status.state === 'ERROR' && styles.powerError]}><Icon name="power" size={24} color={colors.black}/><Text style={styles.powerText}>{active ? 'DISCONNECT' : 'CONNECT'}</Text></Pressable>
    <View style={styles.configCard}><View style={styles.cardLine}><View style={styles.lineIcon}><Icon name="transport" size={18} color={colors.violetSoft}/></View><View style={styles.lineCopy}><Text style={styles.lineLabel}>TRANSPORT</Text><Text style={styles.lineValue}>{transportLabel}</Text></View><Icon name="check" size={19} color={configured ? colors.green : colors.amber}/></View><View style={styles.divider}/><View style={styles.cardLine}><View style={styles.lineIcon}><Icon name="server" size={18} color={colors.cyan}/></View><View style={styles.lineCopy}><Text style={styles.lineLabel}>SERVER / CONFIGURATION</Text><Text style={styles.lineValue}>{configured ? 'Configured' : 'Needs attention'}</Text></View><Text style={[styles.badge, {color: configured ? colors.green : colors.amber}]}>{configured ? 'READY' : 'SETUP'}</Text></View></View>
    <View style={styles.stats}><Stat icon="connection" label="SESSION" value={connected ? duration(status.uptimeSeconds) : '—'} color={connected ? colors.green : colors.text}/><Stat icon="upload" label="UPLOAD" value={bytes(status.uploadBytes)} color={colors.violetSoft}/><Stat icon="download" label="DOWNLOAD" value={bytes(status.downloadBytes)} color={colors.cyan}/></View>
    <Text style={styles.note}>OpenFlux currently routes IPv4 TCP traffic. IPv6 and UDP are not claimed as protected.</Text>
  </ScrollView>;
}
const styles = StyleSheet.create({scroll: {padding: 22, paddingBottom: 26}, header: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, brand: {flexDirection: 'row', alignItems: 'center', gap: 9}, wordmark: {color: colors.text, fontSize: 21, fontWeight: '800', letterSpacing: -.5}, settings: {width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center'}, title: {fontSize: 24, color: colors.text, textAlign: 'center', fontWeight: '800', letterSpacing: -.6}, subtitle: {color: colors.muted, textAlign: 'center', fontSize: 13, marginTop: 8, lineHeight: 19}, error: {backgroundColor: '#2C1520', marginTop: 16, borderRadius: 12, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 8}, errorText: {flex: 1, color: '#FFB2C0', fontSize: 12, lineHeight: 17}, power: {height: 62, borderRadius: 20, marginTop: 24, backgroundColor: colors.violetSoft, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, shadowColor: colors.violet, shadowOpacity: .4, shadowRadius: 18, elevation: 8}, powerOn: {backgroundColor: colors.green}, powerError: {backgroundColor: colors.amber}, powerText: {color: colors.black, fontSize: 14, fontWeight: '900', letterSpacing: 1.4}, configCard: {marginTop: 24, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 20, padding: 15}, cardLine: {flexDirection: 'row', alignItems: 'center'}, lineIcon: {height: 37, width: 37, borderRadius: 11, backgroundColor: colors.surfaceRaised, justifyContent: 'center', alignItems: 'center'}, lineCopy: {flex: 1, marginLeft: 11}, lineLabel: {color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1}, lineValue: {color: colors.text, marginTop: 3, fontSize: 14, fontWeight: '700'}, divider: {height: 1, backgroundColor: colors.border, marginVertical: 14}, badge: {fontSize: 10, fontWeight: '900', letterSpacing: 1}, stats: {marginTop: 18, backgroundColor: colors.surface, borderRadius: 20, padding: 16, flexDirection: 'row', justifyContent: 'space-between'}, note: {color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 18, textAlign: 'center'}});
