import React from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {SettingInput, SettingSwitch} from '../components/SettingRow';
import {Icon} from '../icons/Icon';
import {colors} from '../theme';
import {TransportKind, VpnConfig} from '../types';

function TransportChoice({type, active, title, detail, onPress}: {type: TransportKind; active: boolean; title: string; detail: string; onPress: () => void}) {
  return <Pressable onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><View style={styles.choiceTop}><View style={[styles.choiceIcon, active && styles.choiceIconActive]}><Icon name={type === 'max' ? 'connection' : 'transport'} size={20} color={active ? colors.violetSoft : colors.muted}/></View>{active && <Icon name="check" size={18} color={colors.green}/>}</View><Text style={styles.choiceTitle}>{title}</Text><Text style={styles.choiceDetail}>{detail}</Text></Pressable>;
}
export function SettingsScreen({config, onChange}: {config: VpnConfig; onChange: (patch: Partial<VpnConfig>) => void}) {
  return <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.heading}><Text style={styles.eyebrow}>OPENFLUX</Text><Text style={styles.title}>Configuration</Text><Text style={styles.description}>Credentials are encrypted with Android Keystore-backed storage. They are never placed in debug logs.</Text></View>
    <Text style={styles.section}>TRANSPORT</Text><View style={styles.choices}><TransportChoice type="vyandex" active={config.transport === 'vyandex'} title="Yandex" detail="Yandex Docs VOLGA transport (recommended)" onPress={() => onChange({transport: 'vyandex'})}/><TransportChoice type="yandex" active={config.transport === 'yandex'} title="Yandex (legacy)" detail="Old cursor-based Yandex Docs transport" onPress={() => onChange({transport: 'yandex'})}/><TransportChoice type="max" active={config.transport === 'max'} title="MAX" detail="MAX signaling packet transport" onPress={() => onChange({transport: 'max'})}/></View>
    <View style={styles.panel}>{config.transport === 'yandex' || config.transport === 'vyandex' ? <SettingInput label="Document URL" hint={config.transport === 'vyandex' ? 'The Yandex Docs URL shared with your exit node (must match exactly, opened in the old document editor).' : 'A legacy Yandex Docs URL shared with your exit node.'} value={config.yandexUrl} onChangeText={yandexUrl => onChange({yandexUrl})} keyboardType="url"/> : <><SettingInput label="MAX token" hint="Stored encrypted; keep it private." value={config.maxToken} onChangeText={maxToken => onChange({maxToken})} secure/><SettingInput label="MAX user ID" hint="The remote MAX user ID used by the existing OpenFlux transport." value={config.maxUid} onChangeText={maxUid => onChange({maxUid})} keyboardType="numeric"/></>}</View>
    <Text style={styles.section}>BEHAVIOUR</Text><View style={styles.panel}><SettingSwitch label="Auto reconnect" detail="Keep the real transport handshake retrying after a network interruption." value={config.autoReconnect} onChange={autoReconnect => onChange({autoReconnect})}/><SettingSwitch label="Kill switch" detail="Keeps the TUN active after a transport error so captured TCP traffic cannot escape directly. Android always-on lockdown remains a system setting." value={config.killSwitch} onChange={killSwitch => onChange({killSwitch})}/><SettingSwitch label="Debug mode" detail="Enables technical transport diagnostics only. Tokens and packet payloads remain excluded." value={config.debug} onChange={debug => onChange({debug})}/></View>
    <View style={styles.limit}><Icon name="warning" size={18} color={colors.amber}/><Text style={styles.limitText}>Current OpenFlux core is IPv4/TCP only. DNS over UDP, QUIC and IPv6 are not tunnelled.</Text></View>
  </ScrollView>;
}
const styles = StyleSheet.create({scroll: {padding: 22, paddingBottom: 30}, heading: {marginBottom: 28}, eyebrow: {color: colors.violetSoft, fontSize: 11, letterSpacing: 1.8, fontWeight: '800'}, title: {color: colors.text, fontSize: 30, fontWeight: '800', letterSpacing: -.8, marginTop: 6}, description: {color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 9}, section: {color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 1.3, marginBottom: 10}, choices: {flexDirection: 'row', gap: 8, marginBottom: 18}, choice: {flex: 1, minHeight: 132, padding: 10, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border}, choiceActive: {borderColor: colors.violet, backgroundColor: '#19152A'}, choiceTop: {flexDirection: 'row', justifyContent: 'space-between'}, choiceIcon: {width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: colors.surfaceRaised}, choiceIconActive: {backgroundColor: '#292146'}, choiceTitle: {color: colors.text, fontSize: 13, fontWeight: '800', marginTop: 12}, choiceDetail: {color: colors.muted, fontSize: 10, lineHeight: 13, marginTop: 4}, panel: {backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 19, padding: 15, marginBottom: 26}, limit: {backgroundColor: '#292118', borderRadius: 15, padding: 14, flexDirection: 'row', gap: 10}, limitText: {flex: 1, color: '#F5D399', fontSize: 12, lineHeight: 17}});
